name: 120 Days Stale Check
on:
  schedule:
    - cron: "0 0 1 */2 *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open 120 days with no activity.<br>
            `Stale` issues will automatically be closed 60 days after being marked `Stale` <br>."
          stale-pr-message: "This PR is stale because it has been open 120 days with no activity. <br>
            `Stale` pull requests will automatically be closed 60 days after being marked `Stale` <br>."
          days-before-stale: 120 # 60 days before marking anything stale
          days-before-close: 180
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-pr-labels: "never-stale" # Exempt "never-stale" labels from being marked stale
          exempt-issue-labels: "never-stale" # Exempt "never-stale" labels from being marked stale
